# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qeventlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtaskstate',
            name='task',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
