# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qeventlog', '0004_auto_20160505_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='qevent',
            name='event_index',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='qevent',
            name='retry',
            field=models.SmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
